name: pow
description: Calculates square root, cube root, and any value to a positive or negative power.
version: 0.1.0
repository: https://github.com/alastairlundy/utils

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  decimal: ^2.3.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
