//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasisBox.Cli.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasisBox.Cli.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currently installed version of BasisBox..
        /// </summary>
        internal static string Basis_App_Version {
            get {
                return ResourceManager.GetString("Basis.App.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contents of file {x} was successfully copied to file {y}..
        /// </summary>
        internal static string ConCat_App_Commands_Copy_Success {
            get {
                return ResourceManager.GetString("ConCat.App.Commands.Copy.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the strings you want this file to contain!.
        /// </summary>
        internal static string ConCat_App_Commands_NewFile_Prompt {
            get {
                return ResourceManager.GetString("ConCat.App.Commands.NewFile.Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {x} was successfully saved..
        /// </summary>
        internal static string ConCat_App_Commands_NewFile_Success {
            get {
                return ResourceManager.GetString("ConCat.App.Commands.NewFile.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {x} was sucessfully updated..
        /// </summary>
        internal static string ConCat_App_Commands_UpdateFile_Success {
            get {
                return ResourceManager.GetString("ConCat.App.Commands.UpdateFile.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string ConCat_App_Inputs_No {
            get {
                return ResourceManager.GetString("ConCat.App.Inputs.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string ConCat_App_Inputs_Yes {
            get {
                return ResourceManager.GetString("ConCat.App.Inputs.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want file {x} to be deleted?.
        /// </summary>
        internal static string Del_App_Any_DeleteConfirmation_File {
            get {
                return ResourceManager.GetString("Del.App.Any.DeleteConfirmation.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Y for yes OR N for no..
        /// </summary>
        internal static string Del_App_Any_DeleteConfirmation_YesOrNo {
            get {
                return ResourceManager.GetString("Del.App.Any.DeleteConfirmation.YesOrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force deletion of files or directories.
        /// </summary>
        internal static string Del_App_Any_Parameters_Force_Description {
            get {
                return ResourceManager.GetString("Del.App.Any.Parameters.Force.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete multiple files or directories either recursively or non-recursively..
        /// </summary>
        internal static string Del_App_Commands_Delete_Many_Description {
            get {
                return ResourceManager.GetString("Del.App.Commands.Delete.Many.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a file or director either recursively or non-recursively..
        /// </summary>
        internal static string Del_App_Commands_Delete_Single_Description {
            get {
                return ResourceManager.GetString("Del.App.Commands.Delete.Single.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete empty folders and/or parent folders, recursively or non-recursively.
        ///.
        /// </summary>
        internal static string DelDir_App_Description {
            get {
                return ResourceManager.GetString("DelDir.App.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can file a Bug Report at {x}.
        /// </summary>
        internal static string Exceptions_BugReport_File {
            get {
                return ResourceManager.GetString("Exceptions.BugReport.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this was unintended or unexpected, it would really help us out if you could file a Bug Report..
        /// </summary>
        internal static string Exceptions_BugReport_Request {
            get {
                return ResourceManager.GetString("Exceptions.BugReport.Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot copy more than one existing file into a file. Please use a file appending parameter instead..
        /// </summary>
        internal static string Exceptions_Copying_InvalidExistingArguments {
            get {
                return ResourceManager.GetString("Exceptions.Copying.InvalidExistingArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A non-empty directory of {x} was provided. If this was intentional please use the del command or an equivalent to delete a directory with files or folders in it. If this was not intentional please view the contents of the directory and ensure it is empty before deletion. If the directory was empty please file a bug report for this program at https://github.com/alastairlundy/BasisBox/issues/.
        /// </summary>
        internal static string Exceptions_DirectoryNotEmpty {
            get {
                return ResourceManager.GetString("Exceptions.DirectoryNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate directory {x}. If this directory previously existed it may have been moved or deleted..
        /// </summary>
        internal static string Exceptions_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Exceptions.DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program was unable to find the specified file. If the file exists, consider checking your input for typos or mistakes..
        /// </summary>
        internal static string Exceptions_FileNotFound {
            get {
                return ResourceManager.GetString("Exceptions.FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an exception. Here are the details: {x}.
        /// </summary>
        internal static string Exceptions_Generic {
            get {
                return ResourceManager.GetString("Exceptions.Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid value was provided. Please try again..
        /// </summary>
        internal static string Exceptions_InvalidDeleteConfirmation {
            get {
                return ResourceManager.GetString("Exceptions.InvalidDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid file or directory was passed as an argument..
        /// </summary>
        internal static string Exceptions_InvalidFileOrDirectoryArguments {
            get {
                return ResourceManager.GetString("Exceptions.InvalidFileOrDirectoryArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid file or directory was passed as an argument..
        /// </summary>
        internal static string Exceptions_InvalidFileOrDirectoryArguments1 {
            get {
                return ResourceManager.GetString("Exceptions.InvalidFileOrDirectoryArguments1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory argument passed is not allowed in this program for the safety of your system..
        /// </summary>
        internal static string Exceptions_InvalidSlashCommand {
            get {
                return ResourceManager.GetString("Exceptions.InvalidSlashCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files or directories were provided..
        /// </summary>
        internal static string Exceptions_NoArgumentsProvided {
            get {
                return ResourceManager.GetString("Exceptions.NoArgumentsProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file was provided as an argument to be used..
        /// </summary>
        internal static string Exceptions_NoFileProvided {
            get {
                return ResourceManager.GetString("Exceptions.NoFileProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Operating System DENIED access to the file {x}. You may need to re-run the program with Administrator privileges to perform this operation..
        /// </summary>
        internal static string Exceptions_Permissions_Invalid {
            get {
                return ResourceManager.GetString("Exceptions.Permissions.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The results could not be saved to the file. Please check the exception details for the reason why..
        /// </summary>
        internal static string File_Saved_Failure {
            get {
                return ResourceManager.GetString("File.Saved.Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The results were successfully saved to the file..
        /// </summary>
        internal static string File_Saved_Succes {
            get {
                return ResourceManager.GetString("File.Saved.Succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {x} was deleted..
        /// </summary>
        internal static string Item_Deleted {
            get {
                return ResourceManager.GetString("Item.Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints the name of the current user name..
        /// </summary>
        internal static string LoginName_App_Description {
            get {
                return ResourceManager.GetString("LoginName.App.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates new specified directories with specified parameters..
        /// </summary>
        internal static string NewDir_App_Commands_ManyNewDirs_Description {
            get {
                return ResourceManager.GetString("NewDir.App.Commands.ManyNewDirs.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new specified directory with specified parameters..
        /// </summary>
        internal static string NewDir_App_Commands_SingleNewDir_Description {
            get {
                return ResourceManager.GetString("NewDir.App.Commands.SingleNewDir.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add numbers to lines either from a file or standard input and sent to standard output..
        /// </summary>
        internal static string NLine_App_Description {
            get {
                return ResourceManager.GetString("NLine.App.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count the number of lines, words, characters, and/or bytes in specified files..
        /// </summary>
        internal static string WCount_App_Description {
            get {
                return ResourceManager.GetString("WCount.App.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string WCount_App_Labels_Total {
            get {
                return ResourceManager.GetString("WCount.App.Labels.Total", resourceCulture);
            }
        }
    }
}
