name: round
description: Round a given number to a specified number of decimal places or significant figures
version: 0.0.1
repository: https://github.com/alastairlundy/utils

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  decimal: ^2.3.3
  fixed: ^4.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
