//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCount.Desktop.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WCount.Desktop.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte Count.
        /// </summary>
        internal static string Counting_Labels_Bytes {
            get {
                return ResourceManager.GetString("Counting.Labels.Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Count.
        /// </summary>
        internal static string Counting_Labels_Characters {
            get {
                return ResourceManager.GetString("Counting.Labels.Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Counting_Labels_File_Singular {
            get {
                return ResourceManager.GetString("Counting.Labels.File.Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Count.
        /// </summary>
        internal static string Counting_Labels_Lines {
            get {
                return ResourceManager.GetString("Counting.Labels.Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Count.
        /// </summary>
        internal static string Counting_Labels_Words {
            get {
                return ResourceManager.GetString("Counting.Labels.Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string Results_Labels_Byte_Plural {
            get {
                return ResourceManager.GetString("Results.Labels.Byte.Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte.
        /// </summary>
        internal static string Results_Labels_Byte_Singular {
            get {
                return ResourceManager.GetString("Results.Labels.Byte.Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        internal static string Results_Labels_Character_Plural {
            get {
                return ResourceManager.GetString("Results.Labels.Character.Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        internal static string Results_Labels_Character_Singular {
            get {
                return ResourceManager.GetString("Results.Labels.Character.Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        internal static string Results_Labels_Line_Plural {
            get {
                return ResourceManager.GetString("Results.Labels.Line.Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Results_Labels_Line_Singular {
            get {
                return ResourceManager.GetString("Results.Labels.Line.Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words.
        /// </summary>
        internal static string Results_Labels_Word_Plural {
            get {
                return ResourceManager.GetString("Results.Labels.Word.Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        internal static string Results_Labels_Word_Singular {
            get {
                return ResourceManager.GetString("Results.Labels.Word.Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Settings_Labels_Appearance {
            get {
                return ResourceManager.GetString("Settings.Labels.Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Settings_Labels_Themes_Dark {
            get {
                return ResourceManager.GetString("Settings.Labels.Themes.Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Settings_Labels_Themes_Light {
            get {
                return ResourceManager.GetString("Settings.Labels.Themes.Light", resourceCulture);
            }
        }
    }
}
