//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewDir.Cli.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewDir.Cli.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates new specified directories with specified parameters..
        /// </summary>
        internal static string Commands_ManyNewDir_Description {
            get {
                return ResourceManager.GetString("Commands.ManyNewDir.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new specified directory with specified parameters..
        /// </summary>
        internal static string Commands_NewDir_Description {
            get {
                return ResourceManager.GetString("Commands.NewDir.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory to be created was not specified. If this was not intentional, ensure that you are passing a valid directory as an argument..
        /// </summary>
        internal static string Exceptions_DirectoryNotSpecified {
            get {
                return ResourceManager.GetString("Exceptions.DirectoryNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the directories to be created was not specified. If this was not intentional, ensure that you are passing valid directories as an argument..
        /// </summary>
        internal static string Exceptions_DirectoryNotSpecified_Plural {
            get {
                return ResourceManager.GetString("Exceptions.DirectoryNotSpecified.Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid argument value was passed to the application. The invalid argument value was {x}..
        /// </summary>
        internal static string Exceptions_InvalidArgument {
            get {
                return ResourceManager.GetString("Exceptions.InvalidArgument", resourceCulture);
            }
        }
    }
}
